# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#   
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do 
# not exceed four million, find the sum of the even-valued terms.

even_fib <- function(x) {
  fibs <- c(1,2)
  evens <- c(2)
  while (max(fibs) < x) {
    new_fib <- sum(fibs[length(fibs)], fibs[length(fibs) - 1])
    if (new_fib %% 2 == 0) evens <- c(evens, new_fib)
    fibs <- c(fibs, new_fib)
    # print(new_fib)
  }
  return(sum(evens))
}

even_fib(4000000)